# Generated by Django 2.2.5 on 2019-09-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190908_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
